apiVersion: v1
kind: Service
metadata:
  name: {{ include "cloud-application.fullname" . }}
  annotations:
    dev.okteto.com/auto-ingress: "true"
  labels:
    {{- include "cloud-application.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "cloud-application.selectorLabels" . | nindent 4 }}
